# Generated by Django 5.0.3 on 2024-04-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='date',
        ),
    ]
