# Generated by Django 5.0.3 on 2024-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_style_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='style',
            name='style',
            field=models.CharField(choices=[('M', 'Modern'), ('T', 'Traditional'), ('R', 'Rustic')], default='M', max_length=1, verbose_name='Wedding Style'),
        ),
    ]
