# Generated by Django 5.0.3 on 2024-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_provider_alter_style_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='providers',
            field=models.ManyToManyField(to='main_app.provider'),
        ),
    ]
